import React from "react"
import CallToActionBanner from "./CallToActionBanner"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  CallToActionBanner,
  "https://www.figma.com/design/iFhj20shq9rvgmMjIL1PoP/Sharknado?node-id=239%3A16",
  {
    props: {},
    example: (props) => <CallToActionBanner />,
  },
)
